<?php

namespace Extsalt\Otp\Test\Unit;

use Extsalt\Otp\SMSServiceProvider;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Config;

class TestCase extends \Orchestra\Testbench\TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->withFactories(__DIR__ . '/../../database/factories');
    }

    protected function getPackageProviders($app)
    {
        return [
            SMSServiceProvider::class
        ];
    }

    /**
     * Define environment setup.
     *
     * @param Application $app
     *
     * @return void
     */
    protected function getEnvironmentSetUp($app)
    {
        $app['config']->set('database.default', 'testdb');
        $app['config']->set('database.connections.testdb', [
            'driver' => 'sqlite',
            'database' => ':memory:'
        ]);

        $app['config']->set('sms.NIMBUS_USER_ID', '100285');
        $app['config']->set('sms.NIMBUS_AUTH_KEY', '010hQEHTtR009I2ZpZVT');
        $app['config']->set('sms.NIMBUS_SENDER_ID', 'DIGISM');

        $app['config']->set('sms.MSG91_AUTH_KEY', '010hQEHTtR009I2ZpZVT');
        $app['config']->set('sms.MSG91_SENDER_ID', 'OTPOTP');
    }
}